export const mechanicProfile = {
  id: '1',
  name: 'Ahmet Yılmaz',
  email: 'ahmet.yilmaz@email.com',
  phone: '+90 532 123 45 67',
  address: 'Kadıköy, İstanbul',
  specialties: ['Motor', 'Fren', 'Elektrik', 'Klima'],
  rating: 4.8,
  completedJobs: 156,
  priceRange: '₺150-300',
  workingHours: '08:00 - 18:00',
  experience: '8 yıl',
  isOnline: true,
};

export const mockCarsToRepair = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2018,
    plate: '34 ABC 123',
    customerName: 'Mehmet Demir',
    customerPhone: '+90 532 987 65 43',
    problem: 'Motor arızası, çalışmıyor',
    priority: 'high',
    addedDate: '2024-01-15',
    estimatedPrice: '₺800',
    status: 'waiting',
  },
  {
    id: '2',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2020,
    plate: '06 XYZ 789',
    customerName: 'Ayşe Kaya',
    customerPhone: '+90 533 456 78 90',
    problem: 'Fren balata değişimi',
    priority: 'medium',
    addedDate: '2024-01-16',
    estimatedPrice: '₺350',
    status: 'waiting',
  },
  {
    id: '3',
    brand: 'BMW',
    model: '3 Series',
    year: 2019,
    plate: '35 BMW 456',
    customerName: 'Ali Özkan',
    customerPhone: '+90 534 123 45 67',
    problem: 'Klima çalışmıyor',
    priority: 'low',
    addedDate: '2024-01-17',
    estimatedPrice: '₺450',
    status: 'in_progress',
  },
];

export const mockMessages = [
  {
    id: '1',
    customerName: 'Mehmet Demir',
    message: 'Merhaba, aracımın motor arızası için ne zaman bakabilirsiniz?',
    time: '14:30',
    isRead: false,
    carPlate: '34 ABC 123',
  },
  {
    id: '2',
    customerName: 'Ayşe Kaya',
    message: 'Fren balata işi ne kadar sürer?',
    time: '13:15',
    isRead: true,
    carPlate: '06 XYZ 789',
  },
  {
    id: '3',
    customerName: 'Ali Özkan',
    message: 'Klima tamiri tamamlandı mı?',
    time: '12:45',
    isRead: false,
    carPlate: '35 BMW 456',
  },
];

export const mockOffers = [
  {
    id: '1',
    customerName: 'Fatma Çelik',
    carInfo: '2017 Ford Focus - 34 DEF 456',
    problem: 'Transmisyon arızası',
    offeredPrice: '₺600',
    location: 'Üsküdar, İstanbul',
    distance: '2.3 km',
    urgency: 'high',
    time: '10 dk önce',
  },
  {
    id: '2',
    customerName: 'Hasan Kara',
    carInfo: '2019 Renault Clio - 06 REN 789',
    problem: 'Lastik değişimi',
    offeredPrice: '₺200',
    location: 'Beşiktaş, İstanbul',
    distance: '1.8 km',
    urgency: 'medium',
    time: '25 dk önce',
  },
];

export const mockActiveJobs = [
  {
    id: '1',
    customerName: 'Ali Özkan',
    carInfo: '2019 BMW 3 Series - 35 BMW 456',
    problem: 'Klima çalışmıyor',
    startDate: '2024-01-17',
    estimatedCompletion: '2024-01-18',
    price: '₺450',
    progress: 75,
    status: 'in_progress',
  },
  {
    id: '2',
    customerName: 'Zeynep Yıldız',
    carInfo: '2020 Honda Civic - 34 HON 123',
    problem: 'Fren sistemi bakımı',
    startDate: '2024-01-16',
    estimatedCompletion: '2024-01-17',
    price: '₺300',
    progress: 90,
    status: 'almost_done',
  },
];
